### ISSUE TITLE
Project Section in Home page

### ISSUE THREAD

**Issue by Aniket762** [Aniket762/webwiz-portfolio#11]
## Remove the instagram and linkedin icon and align the github icon along the mid axis. Apply margin between the cards and also verify that the 3 cards are center aligned. And maintain responsiveness
![wr13fix](https://user-images.githubusercontent.com/67703407/115382154-fdab8a00-a1f1-11eb-9800-43ffd9697319.png)

## attach screenshot before sending PR

**Comment by deb2000-sudo** [comment]
I want to contribute assign it to me

**Comment by Aniket762** [comment]
@deb2000-sudo go for it 🚀

**Comment by Aniket762** [comment]
@all-contributors please add @sumana2001  for infrastructure and code

**Comment by zaindewsi** [comment]
is this still needing work to be done? I would like to contribute

**Comment by Aniket762** [comment]
@zaindewsi go for it, I am assigning it to you! 😃

**Comment by poly4concept** [comment]
Hi all, @Aniket762 I don't know if this is still open, I'll love to contribute also

**Comment by Aniket762** [comment]
@poly4concept yes go for it

**Comment by Bartek532** [comment]
@Aniket762  wait, what!? I was the first to do so! 😅

**Comment by Aniket762** [comment]
@Bartek532 bro let everyone contribute 😊it's always nice to see inclusive codebases 😁

**Comment by poly4concept** [comment]
@Aniket762  I have made a pull request regarding the issue days ago, so I am gladly  waiting for  reviews from you and others

**Comment by Aniket762** [comment]
Hey, @poly4concept  sorry for the delay was busy with something else. I have merged your pull request good work! 😁

**Comment by poly4concept** [comment]
Wow, thanks 
I'm glad to be able to contribute here. This is my first open-source contribution.  
l look forward to contributing more in future.
