### ISSUE TITLE
Make a cool *Join Us* banner 

### ISSUE THREAD

**Issue by Aniket762** [Aniket762/webwiz-portfolio#12]
### Make a cool join us banner. Add the logo of webwiz. Add some cool text such as "Technical Club of NITR". Just a side note when the banner will be clicked it will be directed to a Typeform.
![wr14fix](https://user-images.githubusercontent.com/67703407/115382890-d0131080-a1f2-11eb-9202-a8d3d89e2b32.png)

Attach screenshot of your work

**Comment by jameskorah** [comment]
Hey @Aniket762, 

I've made the banner below:
![image](https://user-images.githubusercontent.com/83485518/116805061-8d95e180-aad8-11eb-8422-36f77628a635.png)

Let me know what you think!

**Comment by Aniket762** [comment]
Hey @jameskorah this looks cool send a PR 😃

**Comment by jameskorah** [comment]
Hi Aniket762,

Not sure where you wanted it, I've put it in the Public folder.

**Comment by Aniket762** [comment]
thanks @jameskorah
