### ISSUE TITLE
Style Navbar Mobile View

### ISSUE THREAD

**Issue by sumana2001** [Aniket762/webwiz-portfolio#16]
Add spacing and some hover effect on the menu that opens up when we click the hamburger
![image](https://user-images.githubusercontent.com/63084088/115393583-7ebd4e00-a1ff-11eb-9cb6-d2f25a22d628.png)

**Comment by sayna3311** [comment]
I would like to contribute :)

**Comment by Aniket762** [comment]
@sayna3311 go for it 🚀

**Comment by 895623741x** [comment]
Hi, there! Is anyone still working on this issue? If not, I would like to work on it.

**Comment by Aniket762** [comment]
Hey, @895623741x the issue has been resolved. It's great to know that you wanted to help 😃
