### ISSUE TITLE
Collect all subpages into one and apply a scroll animations

### ISSUE THREAD

**Issue by Bartek532** [Aniket762/webwiz-portfolio#62]
I think multiple subpages are not ideal for this website. What do you think about putting everything on one page and applying appropriate scroll animations?

**Comment by Aniket762** [comment]
Send a screen recording with the animations along with the PR and let's see 😁

**Comment by Bartek532** [comment]
What do you think about AOS?

https://michalsnik.github.io/aos

**Comment by Bartek532** [comment]
I suggest to implement this on one page first and see, how does it fit, what do you think? 😁

**Comment by Aniket762** [comment]
Yes, except the team page everything can be made into one we can do it 😝
