### ISSUE TITLE
Website content

### ISSUE THREAD

**Issue by Bartek532** [Aniket762/webwiz-portfolio#76]
Are there plans to put actual content on the site in the future? If so, I would suggest using headless CMS (e.g. DatoCMS) for content management 😊

**Comment by Aniket762** [comment]
Hey, @Bartek532 actually we are trying to organize a hackathon and we have exams this month so everyone is pretty packed up. Thanks for your suggestion dude 😍 will surely try using Dato. Till it will be great if you can contribute and help us a bit at https://github.com/Hackodisha/hackodisha-web and suggest some good changes which we should look up to. Again thanks a lot for suggesting you are really cool dude 💕

**Comment by Bartek532** [comment]
Thanks 😍 ok, I will check linked project and contribute to it, after all we always can come back here and keep working 😛
